#------------------------------------------------------------
# TU Delft hpc06: PBS
#------------------------------------------------------------

# Cluster host and scheduler options: the defaults come from
# Graham at Compute Canada, running Slurm. Other options can
# be found in the library of snippets,
# `_includes/snippets_library`. To use one, replace options
# below with those in `_config_options.yml` from the
# library. E.g, to customise for hpc06 at TU Delft, running
# PBS, we could replace the options below with those from
# 
# _includes/snippets_library/NL_TUDelft_hpc06_PBS/_config_options.yml
# 
# If your cluster is not represented in the library, please
# copy an existing folder, rename it, and customize for your
# installation. Remember to keep the leading slash on the
# `snippets` variable below!

snippets: "/snippets_library/NL_TUDelft_hpc06_PBS"

local:
  prompt: "[user@laptop ~]$"
  bash_shebang: "#!/usr/bin/env bash"

remote:
  name: "hpc06"
  login: "hpc06.tudelft.net"
  host: "hpc06"
  node: "node"
  location: "Delft University of Technology, The Netherlands"
  homedir: "/home/<netID>"
  user: "<netID>"
  prompt: "[<netID>@hpc06]$"
  bash_shebang: "#!/usr/bin/env bash"

sched:
  name: "PBS"
  submit:
    name: "qsub"
    options: ""
    iopt: ""
  queue:
    debug: "standard"
    testing: "standard"
  status: "qstat"
  flag:
    user: "-u <netID>"
    interactive: "-IVl select=1:ncpus=1"
    name: "-N"
    histdetail: "-f"
    time: "-l"
    queue: "-q"
  del: "qdel"
  interactive: "qsub"
  info: "pbsnodes -a"
  comment: "#PBS"
  hist: "qstat -x"

episode_order:
  - 11-hpc-intro
  - 12-cluster
  - 13-scheduler
  - 14-modules
  - 15-transferring-files
  - 16-parallel
  - 17-resources
  - 18-responsibility

